export class Product {
  constructor(
    public id: number,
    public title: string,
    public description: string,
    public category: string,
    public price: number,
    public discountPercentage: number,
    public rating: number,
    public stock: number,
    public brand: string,
    public tags: string[],
    public image: string,
    public images: string[],
    public availabilityStatus: string,
  ) {}
}

export class ProductsData {
  products: Product[];

  constructor() {
    this.products = [
      new Product(
        1,
        'Essence Mascara Lash Princess',
        'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        'beauty',
        9.99,
        10.48,
        2.56,
        99,
        'Essence',
        ['beauty', 'mascara'],
        'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp',
        ['https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp'],
        'In Stock',
      ),
      new Product(
        2,
        'Eyeshadow Palette with Mirror',
        'The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it is convenient for on-the-go makeup application.',
        'beauty',
        19.99,
        18.19,
        2.86,
        34,
        'Glamour Beauty',
        ['beauty', 'eyeshadow'],
        'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp',
        ['https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp'],
        'In Stock',
      ),
      new Product(
        3,
        'Powder Canister',
        'The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.',
        'beauty',
        14.99,
        9.84,
        4.64,
        89,
        'Velvet Touch',
        ['beauty', 'face powder'],
        'https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp',
        ['https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp'],
        'In Stock',
      ),
      new Product(
        4,
        'Red Lipstick',
        'The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.',
        'beauty',
        12.99,
        12.16,
        4.36,
        91,
        'Chic Cosmetics',
        ['beauty', 'lipstick'],
        'https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp',
        ['https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp'],
        'In Stock',
      ),
      new Product(
        5,
        'Red Nail Polish',
        'The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.',
        'beauty',
        8.99,
        11.44,
        4.32,
        79,
        'Nail Couture',
        ['beauty', 'nail polish'],
        'https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp',
        ['https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp'],
        'In Stock',
      ),
      new Product(
        6,
        'Calvin Klein CK One',
        'CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It is a versatile fragrance suitable for everyday wear.',
        'fragrances',
        49.99,
        1.89,
        4.37,
        29,
        'Calvin Klein',
        ['fragrances', 'perfumes'],
        'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp',
        [
          'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp',
          'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/2.webp',
          'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/3.webp',
        ],
        'In Stock',
      ),
      new Product(
        7,
        'Chanel Coco Noir Eau De',
        'Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.',
        'fragrances',
        129.99,
        16.51,
        4.26,
        58,
        'Chanel',
        ['fragrances', 'perfumes'],
        'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp',
        [
          'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp',
          'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/2.webp',
          'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/3.webp',
        ],
        'In Stock',
      ),
      new Product(
        8,
        'Dior J\'adore',
        'J\'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.',
        'fragrances',
        89.99,
        14.72,
        3.8,
        98,
        'Dior',
        ['fragrances', 'perfumes'],
        'https://cdn.dummyjson.com/product-images/fragrances/dior-j\'adore/thumbnail.webp',
        [
          'https://cdn.dummyjson.com/product-images/fragrances/dior-j\'adore/1.webp',
          'https://cdn.dummyjson.com/product-images/fragrances/dior-j\'adore/2.webp',
          'https://cdn.dummyjson.com/product-images/fragrances/dior-j\'adore/3.webp',
        ],
        'In Stock',
      ),
      new Product(
        9,
        'Dolce Shine Eau de',
        'Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It is a joyful and youthful scent.',
        'fragrances',
        69.99,
        0.62,
        3.96,
        4,
        'Dolce & Gabbana',
        ['fragrances', 'perfumes'],
        'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp',
        [
          'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/1.webp',
          'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/2.webp',
          'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/3.webp',
        ],
        'Low Stock',
      ),
      new Product(
        10,
        'Gucci Bloom Eau de',
        'Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It is a modern and romantic scent.',
        'fragrances',
        79.99,
        14.39,
        2.74,
        91,
        'Gucci',
        ['fragrances', 'perfumes'],
        'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp',
        [
          'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/1.webp',
          'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/2.webp',
          'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/3.webp',
        ],
        'In Stock',
      ),
      new Product(
        11,
        'Annibale Colombo Bed',
        'The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.',
        'furniture',
        1899.99,
        8.57,
        4.77,
        88,
        'Annibale Colombo',
        ['furniture', 'beds'],
        'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp',
        [
          'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/1.webp',
          'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/2.webp',
          'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/3.webp',
        ],
        'In Stock',
      ),
      new Product(
        12,
        'Annibale Colombo Sofa',
        'The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.',
        'furniture',
        2499.99,
        14.4,
        3.92,
        60,
        'Annibale Colombo',
        ['furniture', 'sofas'],
        'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/thumbnail.webp',
        [
          'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/1.webp',
          'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/2.webp',
          'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/3.webp',
        ],
        'In Stock',
      ),
      new Product(
        13,
        'Bedside Table African Cherry',
        'The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.',
        'furniture',
        299.99,
        19.09,
        2.87,
        64,
        'Furniture Co.',
        ['furniture', 'bedside tables'],
        'https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/thumbnail.webp',
        [
          'https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/1.webp',
          'https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/2.webp',
          'https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/3.webp',
        ],
        'In Stock',
      ),
      new Product(
        14,
        'Knoll Saarinen Executive Conference Chair',
        'The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.',
        'furniture',
        499.99,
        2.01,
        4.88,
        26,
        'Knoll',
        ['furniture', 'office chairs'],
        'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp',
        [
          'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/1.webp',
          'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/2.webp',
          'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/3.webp',
        ],
        'In Stock',
      ),
      new Product(
        15,
        'Wooden Bathroom Sink With Mirror',
        'The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.',
        'furniture',
        799.99,
        8.8,
        3.59,
        7,
        'Bath Trends',
        ['furniture', 'bathroom'],
        'https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/thumbnail.webp',
        [
          'https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/1.webp',
          'https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/2.webp',
          'https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/3.webp',
        ],
        'Low Stock',
      ),
      new Product(
        16,
        'Apple',
        'Fresh and crisp apples, perfect for snacking or incorporating into various recipes.',
        'groceries',
        1.99,
        12.62,
        4.19,
        8,
        '',
        ['fruits'],
        'https://cdn.dummyjson.com/product-images/groceries/apple/thumbnail.webp',
        ['https://cdn.dummyjson.com/product-images/groceries/apple/1.webp'],
        'In Stock',
      ),
      new Product(
        17,
        'Beef Steak',
        'High-quality beef steak, great for grilling or cooking to your preferred level of doneness.',
        'groceries',
        12.99,
        9.61,
        4.47,
        86,
        '',
        ['meat'],
        'https://cdn.dummyjson.com/product-images/groceries/beef-steak/thumbnail.webp',
        ['https://cdn.dummyjson.com/product-images/groceries/beef-steak/1.webp'],
        'In Stock',
      ),
      new Product(
        18,
        'Cat Food',
        'Nutritious cat food formulated to meet the dietary needs of your feline friend.',
        'groceries',
        8.99,
        9.58,
        3.13,
        46,
        '',
        ['pet supplies', 'cat food'],
        'https://cdn.dummyjson.com/product-images/groceries/cat-food/thumbnail.webp',
        ['https://cdn.dummyjson.com/product-images/groceries/cat-food/1.webp'],
        'In Stock',
      ),
      new Product(
        19,
        'Chicken Meat',
        'Fresh and tender chicken meat, suitable for various culinary preparations.',
        'groceries',
        9.99,
        13.7,
        3.19,
        97,
        '',
        ['meat'],
        'https://cdn.dummyjson.com/product-images/groceries/chicken-meat/thumbnail.webp',
        [
          'https://cdn.dummyjson.com/product-images/groceries/chicken-meat/1.webp',
          'https://cdn.dummyjson.com/product-images/groceries/chicken-meat/2.webp',
        ],
        'In Stock',
      ),
      new Product(
        20,
        'Cooking Oil',
        'Versatile cooking oil suitable for frying, sauteing, and various culinary applications.',
        'groceries',
        4.99,
        9.33,
        4.8,
        10,
        '',
        ['cooking essentials'],
        'https://cdn.dummyjson.com/product-images/groceries/cooking-oil/thumbnail.webp',
        ['https://cdn.dummyjson.com/product-images/groceries/cooking-oil/1.webp'],
        'In Stock',
      ),
      new Product(
        21,
        'Cucumber',
        'Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.',
        'groceries',
        1.49,
        0.16,
        4.07,
        84,
        '',
        ['vegetables'],
        'https://cdn.dummyjson.com/product-images/groceries/cucumber/thumbnail.webp',
        ['https://cdn.dummyjson.com/product-images/groceries/cucumber/1.webp'],
        'In Stock',
      ),
      new Product(
        22,
        'Dog Food',
        'Specially formulated dog food designed to provide essential nutrients for your canine companion.',
        'groceries',
        10.99,
        10.27,
        4.55,
        71,
        '',
        ['pet supplies', 'dog food'],
        'https://cdn.dummyjson.com/product-images/groceries/dog-food/thumbnail.webp',
        ['https://cdn.dummyjson.com/product-images/groceries/dog-food/1.webp'],
        'In Stock',
      ),
      new Product(
        23,
        'Eggs',
        'Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.',
        'groceries',
        2.99,
        11.05,
        2.53,
        9,
        '',
        ['dairy'],
        'https://cdn.dummyjson.com/product-images/groceries/eggs/thumbnail.webp',
        ['https://cdn.dummyjson.com/product-images/groceries/eggs/1.webp'],
        'In Stock',
      ),
      new Product(
        24,
        'Fish Steak',
        'Quality fish steak, suitable for grilling, baking, or pan-searing.',
        'groceries',
        14.99,
        4.23,
        3.78,
        74,
        '',
        ['seafood'],
        'https://cdn.dummyjson.com/product-images/groceries/fish-steak/thumbnail.webp',
        ['https://cdn.dummyjson.com/product-images/groceries/fish-steak/1.webp'],
        'In Stock',
      ),
      new Product(
        25,
        'Green Bell Pepper',
        'Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.',
        'groceries',
        1.29,
        0.16,
        3.25,
        33,
        '',
        ['vegetables'],
        'https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/thumbnail.webp',
        ['https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/1.webp'],
        'In Stock',
      ),
      new Product(
        26,
        'Green Chili Pepper',
        'Spicy green chili pepper, ideal for adding heat to your favorite recipes.',
        'groceries',
        0.99,
        1.0,
        3.66,
        3,
        '',
        ['vegetables'],
        'https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/thumbnail.webp',
        ['https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/1.webp'],
        'Low Stock',
      ),
      new Product(
        27,
        'Honey Jar',
        'Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food.',
        'groceries',
        6.99,
        14.4,
        3.97,
        34,
        '',
        ['condiments'],
        'https://cdn.dummyjson.com/product-images/groceries/honey-jar/thumbnail.webp',
        ['https://cdn.dummyjson.com/product-images/groceries/honey-jar/1.webp'],
        'In Stock',
      ),
      new Product(
        28,
        'Ice Cream',
        'Creamy and delicious ice cream, available in various flavors for a delightful treat.',
        'groceries',
        5.49,
        8.69,
        3.39,
        27,
        '',
        ['desserts'],
        'https://cdn.dummyjson.com/product-images/groceries/ice-cream/thumbnail.webp',
        [
          'https://cdn.dummyjson.com/product-images/groceries/ice-cream/1.webp',
          'https://cdn.dummyjson.com/product-images/groceries/ice-cream/2.webp',
          'https://cdn.dummyjson.com/product-images/groceries/ice-cream/3.webp',
          'https://cdn.dummyjson.com/product-images/groceries/ice-cream/4.webp',
        ],
        'In Stock',
      ),
      new Product(
        29,
        'Juice',
        'Refreshing fruit juice, packed with vitamins and great for staying hydrated.',
        'groceries',
        3.99,
        12.06,
        3.94,
        50,
        '',
        ['beverages'],
        'https://cdn.dummyjson.com/product-images/groceries/juice/thumbnail.webp',
        ['https://cdn.dummyjson.com/product-images/groceries/juice/1.webp'],
        'In Stock',
      ),
      new Product(
        30,
        'Kiwi',
        'Nutrient-rich kiwi, perfect for snacking or adding a tropical twist to your dishes.',
        'groceries',
        2.49,
        15.22,
        4.93,
        99,
        '',
        ['fruits'],
        'https://cdn.dummyjson.com/product-images/groceries/kiwi/thumbnail.webp',
        ['https://cdn.dummyjson.com/product-images/groceries/kiwi/1.webp'],
        'In Stock',
      ),
    ];
  }

  getById(id: number): Product | undefined {
    return this.products.find((p) => p.id === id);
  }
}
