/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MaterialDay1RouteImport } from './routes/material-day1'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SquirrelsIndexRouteImport } from './routes/squirrels.index'
import { Route as SquirrelsIdRouteImport } from './routes/squirrels.$id'

const MaterialDay1Route = MaterialDay1RouteImport.update({
  id: '/material-day1',
  path: '/material-day1',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SquirrelsIndexRoute = SquirrelsIndexRouteImport.update({
  id: '/squirrels/',
  path: '/squirrels/',
  getParentRoute: () => rootRouteImport,
} as any)
const SquirrelsIdRoute = SquirrelsIdRouteImport.update({
  id: '/squirrels/$id',
  path: '/squirrels/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/material-day1': typeof MaterialDay1Route
  '/squirrels/$id': typeof SquirrelsIdRoute
  '/squirrels/': typeof SquirrelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/material-day1': typeof MaterialDay1Route
  '/squirrels/$id': typeof SquirrelsIdRoute
  '/squirrels': typeof SquirrelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/material-day1': typeof MaterialDay1Route
  '/squirrels/$id': typeof SquirrelsIdRoute
  '/squirrels/': typeof SquirrelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/material-day1'
    | '/squirrels/$id'
    | '/squirrels/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/material-day1' | '/squirrels/$id' | '/squirrels'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/material-day1'
    | '/squirrels/$id'
    | '/squirrels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MaterialDay1Route: typeof MaterialDay1Route
  SquirrelsIdRoute: typeof SquirrelsIdRoute
  SquirrelsIndexRoute: typeof SquirrelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/material-day1': {
      id: '/material-day1'
      path: '/material-day1'
      fullPath: '/material-day1'
      preLoaderRoute: typeof MaterialDay1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squirrels/': {
      id: '/squirrels/'
      path: '/squirrels'
      fullPath: '/squirrels/'
      preLoaderRoute: typeof SquirrelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squirrels/$id': {
      id: '/squirrels/$id'
      path: '/squirrels/$id'
      fullPath: '/squirrels/$id'
      preLoaderRoute: typeof SquirrelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MaterialDay1Route: MaterialDay1Route,
  SquirrelsIdRoute: SquirrelsIdRoute,
  SquirrelsIndexRoute: SquirrelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
